- name: US
  uuid: <解锁项目的uuid>
  domain: us.example.com
  port: 443
- name: JP
  uuid: <解锁项目的uuid>
  domain: jp.example.com
  port: 443
- name: HK
  uuid: <解锁项目的uuid>
  domain: hk.example.com
  port: 443
- name: TW
  uuid: <解锁项目的uuid>
  domain: tw.example.com
  port: 443
- name: dns        #自建节点配置这个
  uuid: <自有解锁项目的uuid>
  domain: dns.example.com
  port: 443
